import {
  ProjectItem,
  ServiceItem,
  PricingPlan,
  PricingComparisonRow,
  FAQItem,
  WorkStep,
  WhyReason,
  TargetAudience,
} from './types';

export const VITEWEB_WHATSAPP_NUMBER = "919511007593";
export const VITEWEB_EMAIL = "siteviaworks@gmail.com";

// SITEVIA WORKS official canonical contact constants
export const SITEVIA_WORKS_WHATSAPP_NUMBER = VITEWEB_WHATSAPP_NUMBER;
export const SITEVIA_WORKS_EMAIL = VITEWEB_EMAIL;
export const SITEVIA_WHATSAPP_NUMBER = VITEWEB_WHATSAPP_NUMBER;
export const SITEVIA_EMAIL = VITEWEB_EMAIL;

export const BUSINESS_TYPES = [
  'Restaurant',
  'Café',
  'Salon / Beauty',
  'Gym / Fitness',
  'Fashion Studio',
  'Local Shop',
  'Clinic / Healthcare',
  'Freelancer',
  'Creator / Photographer',
  'Developer',
  'Student',
  'Startup',
  'Other',
];

export const WEBSITE_TYPES = [
  'Business Website',
  'Restaurant & Café Website',
  'Salon & Beauty Website',
  'Gym & Fitness Website',
  'Portfolio',
  'Landing Page',
];

export const PACKAGES = [
  'Starter — ₹2,999',
  'Business — ₹5,499',
  'Premium — ₹7,999',
  'Not Sure',
];

export const FEATURE_OPTIONS = [
  'WhatsApp Integration',
  'Google Maps',
  'Gallery',
  'Contact / Enquiry Form',
  'Services / Products Section',
  'Animations',
  'Booking Features',
  'Social Media Links',
];

export const BUDGET_OPTIONS = [
  '₹2,999 (Starter Plan)',
  '₹5,499 (Business Plan - Most Popular)',
  '₹7,999 (Premium Plan)',
  'Flexible / Let\'s discuss',
];

export const PAGE_OPTIONS = [
  'Up to 3 Pages (Starter)',
  'Up to 6 Pages (Business)',
  'Up to 10 Pages (Premium)',
];

export const DEMO_PROJECTS: ProjectItem[] = [
  {
    id: 'the-saffron-table',
    name: 'The Saffron Table',
    category: 'business',
    categoryLabel: 'Restaurant',
    tagline: 'Fine Dining & Culinary Experience',
    description: 'Restaurant website focused on menu discovery, location and customer enquiries.',
    url: 'https://the-saffron-table.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    tags: ['Menu Explorer', 'Google Maps', 'WhatsApp Booking', 'Ambiance Gallery'],
    themeColor: '#D97706',
    badge: 'Featured Demo',
    highlights: ['Interactive Menu', 'Direct Table Enquiry', 'Location Pinpoint'],
    mobileMockupType: 'food',
  },
  {
    id: 'lume-beauty',
    name: 'LUMÉ Beauty Studio',
    category: 'business',
    categoryLabel: 'Beauty Studio',
    tagline: 'Luxury Aesthetics & Skincare',
    description: 'Elegant beauty studio experience with services, gallery and contact options.',
    url: 'https://lumebeautystudio.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80',
    tags: ['Service Menu', 'Lookbook Gallery', 'Appointment Request', 'Testimonials'],
    themeColor: '#EC4899',
    badge: 'Luxury Aesthetic',
    highlights: ['Treatment Showcase', 'WhatsApp Consultations', 'Price Guide'],
    mobileMockupType: 'beauty',
  },
  {
    id: 'forge-fitness',
    name: 'FORGE Fitness',
    category: 'business',
    categoryLabel: 'Gym / Fitness',
    tagline: 'High Performance Training Facility',
    description: 'Bold fitness website designed to showcase training and motivate visitors.',
    url: 'https://forge-fitness-opal-six.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
    tags: ['Membership Tiers', 'Trainer Profiles', 'Schedule Grid', 'Trial Pass'],
    themeColor: '#EF4444',
    badge: 'High Impact',
    highlights: ['Bold Visuals', 'Quick Free Trial CTA', 'Facility Tour'],
    mobileMockupType: 'fitness',
  },
  {
    id: 'mera-studio',
    name: 'MERA Studio',
    category: 'business',
    categoryLabel: 'Fashion',
    tagline: 'Contemporary Haute Couture & Pret',
    description: 'Modern fashion-focused website with a clean visual presentation.',
    url: 'https://mera-studio-eta.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Editorial Lookbook', 'Collection Drop', 'Brand Story', 'WhatsApp Order'],
    themeColor: '#6366F1',
    badge: 'Editorial Design',
    highlights: ['Minimalist Aesthetic', 'Collection Gallery', 'Direct Inquiries'],
    mobileMockupType: 'fashion',
  },
  {
    id: 'moss-and-bean',
    name: 'MOSS & BEAN Café',
    category: 'business',
    categoryLabel: 'Café',
    tagline: 'Artisanal Roastery & Botanical Bakes',
    description: 'Warm café experience designed around atmosphere, menu and location.',
    url: 'https://mossbean-cafe1.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Beverage Menu', 'Cozy Ambiance', 'Neighborhood Maps', 'Quick Order'],
    themeColor: '#10B981',
    badge: 'Local Favorite',
    highlights: ['Seasonal Specials', 'Instagram Feed Link', 'Directions & Hours'],
    mobileMockupType: 'cafe',
  },
  {
    id: 'aarav-mehta',
    name: 'Aarav Mehta',
    category: 'portfolio',
    categoryLabel: 'Developer Portfolio',
    tagline: 'Full-Stack Engineer & Cloud Architect',
    description: 'Professional developer portfolio focused on skills and projects.',
    url: 'https://aarav-mehtadev.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    tags: ['Project Case Studies', 'Tech Stack Matrix', 'GitHub Activity', 'Resume Download'],
    themeColor: '#0284C7',
    badge: 'Tech Spec',
    highlights: ['Clean Code Showcase', 'Live Demo Links', 'Contact Hub'],
    mobileMockupType: 'dev',
  },
  {
    id: 'rohan-visuals',
    name: 'Rohan Visuals',
    category: 'portfolio',
    categoryLabel: 'Photographer Portfolio',
    tagline: 'Commercial, Portrait & Travel Photography',
    description: 'Visual portfolio designed to showcase photography work.',
    url: 'https://rohan-visuals.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Full-bleed Gallery', 'Client Galleries', 'Shooting Rates', 'Booking Request'],
    themeColor: '#F59E0B',
    badge: 'Visual First',
    highlights: ['High-Res Image Grid', 'Exhibition History', 'Instant WhatsApp Booking'],
    mobileMockupType: 'photo',
  },
  {
    id: 'aanya-kapoor',
    name: 'Aanya Kapoor',
    category: 'portfolio',
    categoryLabel: 'Designer Portfolio',
    tagline: 'Brand Identity & Product Designer',
    description: 'Creative designer portfolio with a strong visual identity.',
    url: 'https://ananya-kapoor.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Brand Guidelines', 'Case Studies', 'Interactive Prototypes', 'Design System'],
    themeColor: '#8B5CF6',
    badge: 'Creative Showcase',
    highlights: ['Design Process Walkthrough', 'Client Deliverables', 'Contact Form'],
    mobileMockupType: 'design',
  },
  {
    id: 'kabir-digital',
    name: 'Kabir Digital',
    category: 'portfolio',
    categoryLabel: 'Freelancer Portfolio',
    tagline: 'Growth Marketing & Content Strategist',
    description: 'Freelancer portfolio designed to present services and work.',
    url: 'https://kabirdigital1.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Services Breakdown', 'Results & Case Studies', 'Package Bundles', 'Direct WhatsApp'],
    themeColor: '#06B6D4',
    badge: 'Client Magnet',
    highlights: ['Clear Value Propositions', 'Service Tiers', 'Client Testimonial Sections'],
    mobileMockupType: 'freelance',
  },
  {
    id: 'vihaan-sharma',
    name: 'Vihaan Sharma',
    category: 'portfolio',
    categoryLabel: 'Student Portfolio',
    tagline: 'CS Undergraduate & Aspiring AI Engineer',
    description: 'Clean personal portfolio for a student and aspiring professional.',
    url: 'https://vihan-sharma-portfolio1.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    tags: ['Education Timeline', 'Hackathons & Projects', 'Certifications', 'Contact'],
    themeColor: '#14B8A6',
    badge: 'Early Career',
    highlights: ['Academic Highlights', 'Interactive Projects', 'Resume & LinkedIn'],
    mobileMockupType: 'student',
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'business-websites',
    title: 'BUSINESS WEBSITES',
    shortDesc: 'Professional websites that make your business easy to discover and contact.',
    fullDesc: 'Custom layouts tailored to your industry with services overview, team profiles, location maps, and high-conversion contact pathways.',
    iconName: 'Building2',
    features: ['Custom branded layout', 'Mobile-first design', 'WhatsApp integration', 'Google Maps integration', 'Services & products section', 'Deployment'],
    recommendedFor: 'Local businesses, corporate services, clinics, firms',
    websiteTypeVal: 'Business Website',
    startingPrice: '₹2,999',
  },
  {
    id: 'restaurant-cafe-websites',
    title: 'RESTAURANT & CAFÉ WEBSITES',
    shortDesc: 'Menus, galleries, locations and WhatsApp enquiries in one polished experience.',
    fullDesc: 'Visually appetizing digital menus, photo galleries, dining hours, Google Maps directions, and one-tap table reservation enquiries.',
    iconName: 'UtensilsCrossed',
    features: ['Interactive digital menu', 'Photo & food gallery', 'One-tap WhatsApp table booking', 'Google Maps location pin', 'Opening hours banner', 'Deployment'],
    recommendedFor: 'Restaurants, cafés, bakeries, food trucks, cloud kitchens',
    websiteTypeVal: 'Restaurant & Café Website',
    startingPrice: '₹5,499',
  },
  {
    id: 'salon-beauty-websites',
    title: 'SALON & BEAUTY WEBSITES',
    shortDesc: 'Treatment lists, lookbooks, reviews and WhatsApp appointment bookings.',
    fullDesc: 'Stunning visual portfolios and appointment request flows designed to convert social media visitors into loyal salon and spa clients.',
    iconName: 'Sparkles',
    features: ['Service price menu', 'Style lookbook gallery', 'WhatsApp booking', 'Google Maps location', 'Testimonial section', 'Deployment'],
    recommendedFor: 'Salons, spas, beauty studios, dermatologists, wellness clinics',
    websiteTypeVal: 'Salon & Beauty Website',
    startingPrice: '₹5,499',
  },
  {
    id: 'portfolio-websites',
    title: 'PORTFOLIO WEBSITES',
    shortDesc: 'Showcase your work, skills and personal brand professionally.',
    fullDesc: 'Clean, gallery-driven or case-study-based personal websites that establish your credibility and get you hired or booked by clients.',
    iconName: 'Briefcase',
    features: ['Project case studies', 'Resume / CV view & download', 'Skills & tech matrix', 'Direct client enquiry form', 'High-res image galleries', 'Deployment'],
    recommendedFor: 'Developers, designers, photographers, consultants, students',
    websiteTypeVal: 'Portfolio',
    startingPrice: '₹2,999',
  },
  {
    id: 'landing-pages',
    title: 'LANDING PAGES',
    shortDesc: 'Focused pages designed around a specific product, service or campaign.',
    fullDesc: 'High-conversion, single-page experiences built to drive WhatsApp clicks, phone calls, registrations, or ad campaign conversions.',
    iconName: 'Target',
    features: ['Single-focus conversion goal', 'Fast mobile loading speed', 'Compelling benefit hierarchy', 'Sticky mobile CTA', 'Social proof layouts', 'Deployment'],
    recommendedFor: 'Product launches, marketing campaigns, events, coaches',
    websiteTypeVal: 'Landing Page',
    startingPrice: '₹2,999',
  },
];

export const WHY_REASONS: WhyReason[] = [
  {
    number: '01',
    title: 'RESPONSIVE WEBSITES',
    description: 'Designed around the way your customers actually browse — fast, fluid, and crisp on all smartphones, tablets, and desktops.',
  },
  {
    number: '02',
    title: 'CUSTOM MODERN DESIGN',
    description: 'Every layout is tailored to your business identity and audience without generic template clutter.',
  },
  {
    number: '03',
    title: 'WHATSAPP INTEGRATION',
    description: 'Direct WhatsApp links make it effortless for customers to message, inquire, and order instantly.',
  },
  {
    number: '04',
    title: 'SEO BASICS & GOOGLE MAPS',
    description: 'Clean semantic structure, metadata, and pinpointed Google Maps so local customers find and reach you easily.',
  },
  {
    number: '05',
    title: 'FAST DELIVERY',
    description: 'Standard packages are developed and deployed in 3 to 7 days with live staging previews along the way.',
  },
  {
    number: '06',
    title: 'POST-LAUNCH SUPPORT',
    description: 'Dedicated technical warranty for up to 1.5 years ensures your contact forms, links, and updates run smoothly.',
  },
];

export const HOW_IT_WORKS: WorkStep[] = [
  {
    step: '01',
    title: 'Tell Us Your Requirement',
    description: 'Share your business details, required pages, and preferred style.',
    detail: 'Tell us about your business, reference websites, services, and color preferences via a quick WhatsApp chat or brief form.',
  },
  {
    step: '02',
    title: 'Design',
    description: 'We craft and develop your custom, mobile-first website.',
    detail: 'We structure the page hierarchy, build the responsive interface, and configure WhatsApp triggers, forms, and Google Maps.',
  },
  {
    step: '03',
    title: 'Review',
    description: 'You test the live staging site and request revisions.',
    detail: 'You review the interactive staging preview on your phone and computer. We adjust text, colors, and layout until you are satisfied.',
  },
  {
    step: '04',
    title: 'Launch',
    description: 'Your website goes live on your domain with full support.',
    detail: 'We connect your custom domain, configure fast cloud hosting with free SSL, perform final launch checks, and activate your post-launch support.',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: '₹2,999',
    priceNum: 2999,
    purpose: 'Get Online',
    subtitle: 'Establish a credible, fast mobile presence for small businesses & creators.',
    pages: '3 Pages',
    adminPanelType: 'No Admin Panel',
    adminPanelDesc: 'Suitable for a simple, fast business website. Website content updates can be handled directly by SITEVIA WORKS.',
    features: [
      '3 Custom Pages',
      'No Admin Panel (Clean Static Build)',
      'Content Updates Handled by Us',
      'Mobile Responsive & Fast',
      'WhatsApp Quick Connect',
      'Basic SEO & Search Ready',
      '1 Design Change Included',
      '6 Months Dedicated Support',
    ],
    ctaText: 'Choose Starter →',
    websiteTypeVal: 'Starter — ₹2,999',
  },
  {
    id: 'business',
    name: 'Business',
    price: '₹5,499',
    priceNum: 5499,
    purpose: 'Grow Your Business',
    subtitle: 'Dynamic business website with client admin panel to edit content & track leads.',
    badge: 'Most Popular',
    isPopular: true,
    pages: '6 Pages',
    adminPanelType: 'Basic Admin Panel Included',
    adminPanelDesc: 'Simple & non-technical: manage basic website content (text & images) and review customer enquiries.',
    features: [
      '6 Custom Pages',
      'Basic Admin Panel (Non-Tech Friendly)',
      'Edit Website Text, Images & Banners',
      'Customer Enquiry Management',
      'WhatsApp & Interactive Contact Form',
      'Basic SEO & Google Maps Embed',
      '3 Design Changes Included',
      '12 Months Dedicated Support',
    ],
    ctaText: 'Choose Business →',
    websiteTypeVal: 'Business — ₹5,499',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: '₹7,999',
    priceNum: 7999,
    purpose: 'Build Your Brand',
    subtitle: 'High-end brand presence with full advanced admin dashboard and deep management.',
    pages: '10 Pages',
    adminPanelType: 'Full / Advanced Admin Panel',
    adminPanelDesc: 'Comprehensive dashboard: enquiry CRM, content/media manager, services/products catalog, site settings & basic analytics.',
    features: [
      '10 Custom Pages',
      'Full / Advanced Admin Panel & Dashboard',
      'Enquiry Management & Lead Tracking',
      'Content, Media & Services/Products Manager',
      'Website Settings & On-Page SEO Controls',
      'Basic Analytics & Performance Dashboard',
      '5 Design Changes Included',
      '18 Months Dedicated Support',
    ],
    ctaText: 'Choose Premium →',
    websiteTypeVal: 'Premium — ₹7,999',
  },
];

export const PRICING_COMPARISON_ROWS: PricingComparisonRow[] = [
  {
    feature: 'Pages Included',
    starter: '3',
    business: '6',
    premium: '10',
  },
  {
    feature: 'Admin Panel',
    starter: 'Not Included',
    business: 'Basic Admin Panel',
    premium: 'Full / Advanced Panel',
  },
  {
    feature: 'Content Management',
    starter: 'Handled by SITEVIA WORKS',
    business: 'Edit Text & Images',
    premium: 'Full Content & Media Library',
  },
  {
    feature: 'Customer Enquiry Management',
    starter: 'Via WhatsApp Direct',
    business: 'Basic Leads Inbox',
    premium: 'Advanced Enquiry & Lead CRM',
  },
  {
    feature: 'Services / Products Management',
    starter: false,
    business: false,
    premium: 'Catalog & Services Editor',
  },
  {
    feature: 'Website Settings & Controls',
    starter: false,
    business: 'Basic Contact Info',
    premium: 'Full Settings & SEO Controls',
  },
  {
    feature: 'Analytics & Dashboard',
    starter: false,
    business: false,
    premium: 'Basic Analytics & Insights',
  },
  {
    feature: 'Mobile Responsive',
    starter: true,
    business: true,
    premium: true,
  },
  {
    feature: 'WhatsApp Integration',
    starter: true,
    business: true,
    premium: true,
  },
  {
    feature: 'Contact Form',
    starter: false,
    business: true,
    premium: true,
  },
  {
    feature: 'Google Maps Integration',
    starter: false,
    business: true,
    premium: true,
  },
  {
    feature: 'Basic SEO Setup',
    starter: true,
    business: true,
    premium: true,
  },
  {
    feature: 'Design Polish & Motion',
    starter: 'Standard Fast',
    business: 'Custom Responsive',
    premium: 'Premium Bespoke Animations',
  },
  {
    feature: 'Design Changes Included',
    starter: '1',
    business: '3',
    premium: '5',
  },
  {
    feature: 'Dedicated Warranty Support',
    starter: '6 months',
    business: '12 months',
    premium: '18 months',
  },
  {
    feature: 'Domain & Hosting Cost',
    starter: 'Paid by Client',
    business: 'Paid by Client',
    premium: 'Paid by Client',
  },
  {
    feature: 'Setup Assistance',
    starter: 'Free Included',
    business: 'Free Included',
    premium: 'Free Included',
  },
];

export const WHAT_YOU_GET_ITEMS = [
  {
    title: 'Mobile-Responsive Website',
    desc: 'Fluid layout optimized for phones, tablets, and desktops.',
    iconName: 'Smartphone',
  },
  {
    title: 'WhatsApp Integration',
    desc: 'Direct click-to-chat inquiry buttons for fast mobile leads.',
    iconName: 'MessageCircle',
  },
  {
    title: 'SEO-Ready Structure',
    desc: 'Semantic HTML, OpenGraph tags, and Google crawl-ready setup.',
    iconName: 'Search',
  },
  {
    title: 'Contact Section',
    desc: 'Lead forms, direct call buttons, and email communication.',
    iconName: 'Mail',
  },
  {
    title: 'Deployment Assistance',
    desc: 'Domain setup help connecting to fast cloud hosting with SSL.',
    iconName: 'Globe',
  },
  {
    title: 'Social Links',
    desc: 'Clean routing to your verified social profiles and Google Maps.',
    iconName: 'Share2',
  },
  {
    title: 'Performance-Focused Design',
    desc: 'Clean code and lightweight assets for fast mobile loading.',
    iconName: 'Zap',
  },
  {
    title: 'Post-Launch Support',
    desc: '6 to 18 months of technical warranty and maintenance support.',
    iconName: 'ShieldCheck',
  },
];

export const TARGET_AUDIENCES: TargetAudience[] = [
  {
    id: 'restaurants',
    title: 'Restaurants & Dining',
    description: 'Digital food menus, chef specials, location maps, and instant WhatsApp table reservations.',
    iconName: 'UtensilsCrossed',
    sampleWebsite: 'The Saffron Table',
    featuresNeeded: ['Interactive Menu', 'Google Maps', 'WhatsApp Booking'],
  },
  {
    id: 'cafes',
    title: 'Cafés & Bakeries',
    description: 'Cozy ambiance showcases, daily pastry drops, specialty roasts, and directions.',
    iconName: 'Coffee',
    sampleWebsite: 'Moss & Bean Café',
    featuresNeeded: ['Ambiance Gallery', 'Coffee Menu', 'Opening Hours'],
  },
  {
    id: 'beauty',
    title: 'Beauty & Hair Studios',
    description: 'Treatment price lists, style lookbooks, customer reviews, and appointment enquiries.',
    iconName: 'Sparkles',
    sampleWebsite: 'LUMÉ Beauty Studio',
    featuresNeeded: ['Service Cards', 'Style Gallery', 'WhatsApp Consults'],
  },
  {
    id: 'gyms',
    title: 'Gyms & Fitness Centers',
    description: 'High-energy training programs, coach bios, membership plans, and free trial passes.',
    iconName: 'Dumbbell',
    sampleWebsite: 'FORGE Fitness',
    featuresNeeded: ['Class Schedules', 'Trainer Showcase', 'Free Pass CTA'],
  },
  {
    id: 'fashion',
    title: 'Fashion Brands',
    description: 'Clean editorial lookbooks, seasonal drops, sizing guides, and direct order links.',
    iconName: 'Shirt',
    sampleWebsite: 'MERA Studio',
    featuresNeeded: ['Lookbook Grid', 'WhatsApp Orders', 'Collection Stories'],
  },
  {
    id: 'shops',
    title: 'Local Retail Shops',
    description: 'Product showcases, store location pins, stock enquiry lines, and promotional banners.',
    iconName: 'Store',
    sampleWebsite: 'Retail Demo',
    featuresNeeded: ['Store Hours', 'Product Catalog', 'Direct Contact'],
  },
  {
    id: 'freelancers',
    title: 'Freelancers & Consultants',
    description: 'Service packages, client proof, case study breakdowns, and direct project enquiry lines.',
    iconName: 'Laptop',
    sampleWebsite: 'Kabir Digital',
    featuresNeeded: ['Services Breakdown', 'Case Studies', 'Direct Booking'],
  },
  {
    id: 'creators',
    title: 'Creators & Photographers',
    description: 'High-resolution photo & video galleries, booking rates, and media kit links.',
    iconName: 'Camera',
    sampleWebsite: 'Rohan Visuals',
    featuresNeeded: ['Full-Bleed Gallery', 'Rate Card', 'Instant Enquiries'],
  },
  {
    id: 'developers',
    title: 'Developers & Engineers',
    description: 'Live interactive projects, GitHub activity links, tech stacks, and resume downloads.',
    iconName: 'Code',
    sampleWebsite: 'Aarav Mehta',
    featuresNeeded: ['Live Project Demos', 'Tech Stack Pills', 'Resume Download'],
  },
  {
    id: 'students',
    title: 'Students & Graduates',
    description: 'Clean academic profiles, hackathon projects, research papers, and recruiter contact.',
    iconName: 'GraduationCap',
    sampleWebsite: 'Vihaan Sharma',
    featuresNeeded: ['Project Showcase', 'Academic Timeline', 'LinkedIn Link'],
  },
  {
    id: 'startups',
    title: 'Startups & New Brands',
    description: 'High-converting product landing pages, investor-ready presentations, and waitlist forms.',
    iconName: 'Rocket',
    sampleWebsite: 'Startup Launch',
    featuresNeeded: ['Value Prop Highlights', 'Waitlist / Contact', 'Feature Demos'],
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: 'faq-what-is-included',
    question: 'What is included in each website package?',
    answer: 'Every SITEVIA WORKS package includes a custom-designed, mobile-first website, direct WhatsApp inquiry routing, contact sections, Google Maps pin integration (Business & Premium), basic on-page SEO metadata, deployment on high-speed global infrastructure with free SSL, and post-launch technical warranty support (6 months for Starter, 1 year for Business, 1.5 years for Premium).',
  },
  {
    id: 'faq-admin-panel',
    question: 'Do I get an Admin Panel to manage my website?',
    answer: 'Yes, based on the plan you choose: Starter (₹2,999) does not include an admin panel and is ideal for a clean, static professional site where SITEVIA WORKS handles content updates for you. Business (₹5,499) includes a simple, non-technical Basic Admin Panel to edit text, images, and review enquiries. Premium (₹7,999) includes a Full Advanced Admin Dashboard with enquiry management, content/media controls, services/products management, website settings, and visitor analytics.',
  },
  {
    id: 'faq-pricing',
    question: 'How much does a website cost and are there recurring platform fees?',
    answer: 'Our pricing is a transparent, one-time investment with zero recurring platform commissions: Starter at ₹2,999 (up to 3 custom pages, 6 months support), Business at ₹5,499 (up to 6 custom pages, 1 year support — Most Popular), and Premium at ₹7,999 (up to 10 custom pages with advanced interactions, 1.5 years support). You never pay monthly website builder subscriptions to us.',
  },
  {
    id: 'faq-delivery-time',
    question: 'What is the delivery time?',
    answer: 'Starter websites are delivered in 3 to 4 business days. Business websites typically take 5 to 6 business days. Premium and multi-page projects take 7 to 9 business days. We provide a live staging preview link so you can review the website before launch.',
  },
  {
    id: 'faq-domain-hosting',
    question: 'Are domain and hosting charges included in the package?',
    answer: 'Domain name registration and hosting charges are paid directly by the client to their selected provider (such as GoDaddy, Hostinger, Namecheap, etc.). SITEVIA WORKS provides complete, free setup assistance to help you choose the right domain, configure DNS records, and connect fast cloud hosting with SSL.',
  },
  {
    id: 'faq-revisions',
    question: 'Can I request revisions before the website goes live?',
    answer: 'Yes! Every project includes a dedicated staging review phase. We share a private staging URL so you can test the website on your phone and computer. We refine copy, color schemes, imagery, and layout based on your feedback before connecting the final domain.',
  },
  {
    id: 'faq-maintenance-support',
    question: 'How do maintenance and post-launch support work?',
    answer: 'Every package includes dedicated post-launch technical warranty support (6 months for Starter, 1 year for Business, 1.5 years for Premium). Support includes technical bug fixes, broken-link checks, integration troubleshooting, and minor content updates. New pages, redesigns, or major feature additions are charged separately.',
  },
  {
    id: 'faq-domain-renewals',
    question: 'Who manages and pays for domain and hosting renewals?',
    answer: 'Domain and hosting accounts are registered under your own name and account, so all annual renewal fees are paid directly by you to your service provider. SITEVIA WORKS charges only a transparent, one-time development fee with zero monthly platform subscriptions.',
  },
  {
    id: 'faq-payment-process',
    question: 'What is your payment process?',
    answer: 'We follow a simple, transparent milestone structure: 50% upfront deposit to initiate planning, design, and development, and the remaining 50% only after you review and approve the live staging site before official domain launch. Payments are made via secure UPI or direct bank transfer with immediate receipts.',
  },
  {
    id: 'faq-whatsapp-integration',
    question: 'How does the WhatsApp integration work?',
    answer: 'We configure custom one-tap WhatsApp trigger buttons and action bars. When a customer taps to inquire, book a table, or request an appointment, their WhatsApp app opens automatically with a pre-composed message detailing their inquiry, sent straight to your business number.',
  },
  {
    id: 'faq-industry-fit',
    question: 'Can you build a website for my specific business or industry?',
    answer: 'Yes! We build tailored websites for restaurants, cafés, salons, beauty clinics, gyms, fitness coaches, boutiques, fashion brands, local retail stores, doctor clinics, freelance consultants, creators, and professionals. Each site is customized for its target customer journey.',
  },
];
