import {
  ProjectItem,
  ServiceItem,
  PricingPlan,
  FAQItem,
  WorkStep,
  WhyReason,
  TargetAudience,
} from './types';

export const VITEWEB_WHATSAPP_NUMBER = "919511007593";
export const VITEWEB_EMAIL = "mohit926631@gmail.com";
export const VITEWEB_INSTAGRAM = "https://instagram.com";
export const VITEWEB_GITHUB = "https://github.com";

// Compatibility aliases
export const WEBVIA_WHATSAPP_NUMBER = VITEWEB_WHATSAPP_NUMBER;
export const WEBVIA_EMAIL = VITEWEB_EMAIL;
export const WEBVIA_INSTAGRAM = VITEWEB_INSTAGRAM;
export const WEBVIA_GITHUB = VITEWEB_GITHUB;
export const SITEVIA_WHATSAPP_NUMBER = VITEWEB_WHATSAPP_NUMBER;
export const SITEVIA_EMAIL = VITEWEB_EMAIL;
export const SITEVIA_INSTAGRAM = VITEWEB_INSTAGRAM;
export const SITEVIA_GITHUB = VITEWEB_GITHUB;

export const BUSINESS_TYPES = [
  'Restaurant',
  'Café',
  'Salon / Beauty',
  'Gym / Fitness',
  'Fashion Studio',
  'Local Shop',
  'Clinic / Healthcare',
  'Freelancer',
  'Creator / Photographer',
  'Developer',
  'Student',
  'Startup',
  'Other',
];

export const WEBSITE_TYPES = [
  'Business Website',
  'Restaurant & Café Website',
  'Salon & Beauty Website',
  'Gym & Fitness Website',
  'Portfolio',
  'Landing Page',
];

export const PACKAGES = [
  'Starter — ₹1,999',
  'Business — ₹3,499',
  'Professional — ₹5,999',
  'Not Sure',
];

export const FEATURE_OPTIONS = [
  'WhatsApp Integration',
  'Google Maps',
  'Gallery',
  'Contact / Enquiry Form',
  'Services / Products Section',
  'Animations',
  'Booking Features',
  'Social Media Links',
];

export const BUDGET_OPTIONS = [
  '₹1,999 (Starter Plan)',
  '₹3,499 (Business Plan - Most Popular)',
  '₹5,999 (Professional Plan)',
  'Flexible / Let\'s discuss',
];

export const PAGE_OPTIONS = [
  '1–3 Pages (Starter)',
  '4–7 Pages (Business)',
  '7–10+ Pages (Professional)',
];

export const DEMO_PROJECTS: ProjectItem[] = [
  {
    id: 'the-saffron-table',
    name: 'The Saffron Table',
    category: 'business',
    categoryLabel: 'Restaurant',
    tagline: 'Fine Dining & Culinary Experience',
    description: 'Restaurant website focused on menu discovery, location and customer enquiries.',
    url: 'https://the-saffron-table.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    tags: ['Menu Explorer', 'Google Maps', 'WhatsApp Booking', 'Ambiance Gallery'],
    themeColor: '#D97706',
    badge: 'Featured Demo',
    highlights: ['Interactive Menu', 'Direct Table Enquiry', 'Location Pinpoint'],
    mobileMockupType: 'food',
  },
  {
    id: 'lume-beauty',
    name: 'LUMÉ Beauty Studio',
    category: 'business',
    categoryLabel: 'Beauty Studio',
    tagline: 'Luxury Aesthetics & Skincare',
    description: 'Elegant beauty studio experience with services, gallery and contact options.',
    url: 'https://lumebeautystudio.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80',
    tags: ['Service Menu', 'Lookbook Gallery', 'Appointment Request', 'Testimonials'],
    themeColor: '#EC4899',
    badge: 'Luxury Aesthetic',
    highlights: ['Treatment Showcase', 'WhatsApp Consultations', 'Price Guide'],
    mobileMockupType: 'beauty',
  },
  {
    id: 'forge-fitness',
    name: 'FORGE Fitness',
    category: 'business',
    categoryLabel: 'Gym / Fitness',
    tagline: 'High Performance Training Facility',
    description: 'Bold fitness website designed to showcase training and motivate visitors.',
    url: 'https://forge-fitness-opal-six.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
    tags: ['Membership Tiers', 'Trainer Profiles', 'Schedule Grid', 'Trial Pass'],
    themeColor: '#EF4444',
    badge: 'High Impact',
    highlights: ['Bold Visuals', 'Quick Free Trial CTA', 'Facility Tour'],
    mobileMockupType: 'fitness',
  },
  {
    id: 'mera-studio',
    name: 'MERA Studio',
    category: 'business',
    categoryLabel: 'Fashion',
    tagline: 'Contemporary Haute Couture & Pret',
    description: 'Modern fashion-focused website with a clean visual presentation.',
    url: 'https://mera-studio-eta.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Editorial Lookbook', 'Collection Drop', 'Brand Story', 'WhatsApp Order'],
    themeColor: '#6366F1',
    badge: 'Editorial Design',
    highlights: ['Minimalist Aesthetic', 'Collection Gallery', 'Direct Inquiries'],
    mobileMockupType: 'fashion',
  },
  {
    id: 'moss-and-bean',
    name: 'MOSS & BEAN Café',
    category: 'business',
    categoryLabel: 'Café',
    tagline: 'Artisanal Roastery & Botanical Bakes',
    description: 'Warm café experience designed around atmosphere, menu and location.',
    url: 'https://mossbean-cafe1.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Beverage Menu', 'Cozy Ambiance', 'Neighborhood Maps', 'Quick Order'],
    themeColor: '#10B981',
    badge: 'Local Favorite',
    highlights: ['Seasonal Specials', 'Instagram Feed Link', 'Directions & Hours'],
    mobileMockupType: 'cafe',
  },
  {
    id: 'aarav-mehta',
    name: 'Aarav Mehta',
    category: 'portfolio',
    categoryLabel: 'Developer Portfolio',
    tagline: 'Full-Stack Engineer & Cloud Architect',
    description: 'Professional developer portfolio focused on skills and projects.',
    url: 'https://aarav-mehtadev.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    tags: ['Project Case Studies', 'Tech Stack Matrix', 'GitHub Activity', 'Resume Download'],
    themeColor: '#0284C7',
    badge: 'Tech Spec',
    highlights: ['Clean Code Showcase', 'Live Demo Links', 'Contact Hub'],
    mobileMockupType: 'dev',
  },
  {
    id: 'rohan-visuals',
    name: 'Rohan Visuals',
    category: 'portfolio',
    categoryLabel: 'Photographer Portfolio',
    tagline: 'Commercial, Portrait & Travel Photography',
    description: 'Visual portfolio designed to showcase photography work.',
    url: 'https://rohan-visuals.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Full-bleed Gallery', 'Client Galleries', 'Shooting Rates', 'Booking Request'],
    themeColor: '#F59E0B',
    badge: 'Visual First',
    highlights: ['High-Res Image Grid', 'Exhibition History', 'Instant WhatsApp Booking'],
    mobileMockupType: 'photo',
  },
  {
    id: 'aanya-kapoor',
    name: 'Aanya Kapoor',
    category: 'portfolio',
    categoryLabel: 'Designer Portfolio',
    tagline: 'Brand Identity & Product Designer',
    description: 'Creative designer portfolio with a strong visual identity.',
    url: 'https://ananya-kapoor.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Brand Guidelines', 'Case Studies', 'Interactive Prototypes', 'Design System'],
    themeColor: '#8B5CF6',
    badge: 'Creative Showcase',
    highlights: ['Design Process Walkthrough', 'Client Deliverables', 'Contact Form'],
    mobileMockupType: 'design',
  },
  {
    id: 'kabir-digital',
    name: 'Kabir Digital',
    category: 'portfolio',
    categoryLabel: 'Freelancer Portfolio',
    tagline: 'Growth Marketing & Content Strategist',
    description: 'Freelancer portfolio designed to present services and work.',
    url: 'https://kabirdigital1.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Services Breakdown', 'Results & Case Studies', 'Package Bundles', 'Direct WhatsApp'],
    themeColor: '#06B6D4',
    badge: 'Client Magnet',
    highlights: ['Clear Value Propositions', 'Service Tiers', 'Client Testimonial Sections'],
    mobileMockupType: 'freelance',
  },
  {
    id: 'vihaan-sharma',
    name: 'Vihaan Sharma',
    category: 'portfolio',
    categoryLabel: 'Student Portfolio',
    tagline: 'CS Undergraduate & Aspiring AI Engineer',
    description: 'Clean personal portfolio for a student and aspiring professional.',
    url: 'https://vihan-sharma-portfolio1.vercel.app/',
    previewImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    tags: ['Education Timeline', 'Hackathons & Projects', 'Certifications', 'Contact'],
    themeColor: '#14B8A6',
    badge: 'Early Career',
    highlights: ['Academic Highlights', 'Interactive Projects', 'Resume & LinkedIn'],
    mobileMockupType: 'student',
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'business-websites',
    title: 'BUSINESS WEBSITES',
    shortDesc: 'Professional websites that make your business easy to discover and contact.',
    fullDesc: 'Custom layouts tailored to your industry with services overview, team profiles, location maps, and high-conversion contact pathways.',
    iconName: 'Building2',
    features: ['Custom branded layout', 'Mobile-first design', 'WhatsApp integration', 'Google Maps integration', 'Services & products section', 'Deployment'],
    recommendedFor: 'Local businesses, corporate services, clinics, firms',
    websiteTypeVal: 'Business Website',
    startingPrice: '₹1,999',
  },
  {
    id: 'restaurant-cafe-websites',
    title: 'RESTAURANT & CAFÉ WEBSITES',
    shortDesc: 'Menus, galleries, locations and WhatsApp enquiries in one polished experience.',
    fullDesc: 'Visually appetizing digital menus, photo galleries, dining hours, Google Maps directions, and one-tap table reservation enquiries.',
    iconName: 'UtensilsCrossed',
    features: ['Interactive digital menu', 'Photo & food gallery', 'One-tap WhatsApp table booking', 'Google Maps location pin', 'Opening hours banner', 'Deployment'],
    recommendedFor: 'Restaurants, cafés, bakeries, food trucks, cloud kitchens',
    websiteTypeVal: 'Restaurant & Café Website',
    startingPrice: '₹3,499',
  },
  {
    id: 'salon-beauty-websites',
    title: 'SALON & BEAUTY WEBSITES',
    shortDesc: 'Treatment lists, lookbooks, reviews and WhatsApp appointment bookings.',
    fullDesc: 'Stunning visual portfolios and appointment request flows designed to convert social media visitors into loyal salon and spa clients.',
    iconName: 'Sparkles',
    features: ['Service price menu', 'Style lookbook gallery', 'WhatsApp booking', 'Google Maps location', 'Testimonial section', 'Deployment'],
    recommendedFor: 'Salons, spas, beauty studios, dermatologists, wellness clinics',
    websiteTypeVal: 'Salon & Beauty Website',
    startingPrice: '₹3,499',
  },
  {
    id: 'portfolio-websites',
    title: 'PORTFOLIO WEBSITES',
    shortDesc: 'Showcase your work, skills and personal brand professionally.',
    fullDesc: 'Clean, gallery-driven or case-study-based personal websites that establish your credibility and get you hired or booked by clients.',
    iconName: 'Briefcase',
    features: ['Project case studies', 'Resume / CV view & download', 'Skills & tech matrix', 'Direct client enquiry form', 'High-res image galleries', 'Deployment'],
    recommendedFor: 'Developers, designers, photographers, consultants, students',
    websiteTypeVal: 'Portfolio',
    startingPrice: '₹1,999',
  },
  {
    id: 'landing-pages',
    title: 'LANDING PAGES',
    shortDesc: 'Focused pages designed around a specific product, service or campaign.',
    fullDesc: 'High-conversion, single-page experiences built to drive WhatsApp clicks, phone calls, registrations, or ad campaign conversions.',
    iconName: 'Target',
    features: ['Single-focus conversion goal', 'Fast 1-second load times', 'Compelling benefit hierarchy', 'Sticky mobile CTA', 'Social proof layouts', 'Deployment'],
    recommendedFor: 'Product launches, marketing campaigns, events, coaches',
    websiteTypeVal: 'Landing Page',
    startingPrice: '₹1,999',
  },
];

export const WHY_REASONS: WhyReason[] = [
  {
    number: '01',
    title: 'CUSTOM MODERN DESIGN',
    description: 'Every website is shaped with clean layouts and typography tailored to your business.',
  },
  {
    number: '02',
    title: 'MOBILE-FIRST RESPONSIVE',
    description: 'Designed around the way your customers actually browse — fast and smooth on phones.',
  },
  {
    number: '03',
    title: 'WHATSAPP INTEGRATION',
    description: 'Direct WhatsApp links make it effortless for customers to message and enquire instantly.',
  },
  {
    number: '04',
    title: 'GOOGLE MAPS & LOCATION',
    description: 'Pinpoint your store, clinic, or restaurant on Google Maps for easy customer directions.',
  },
  {
    number: '05',
    title: 'GALLERY & SERVICES',
    description: 'Highlight your top services, products, lookbooks, and customer reviews with ease.',
  },
  {
    number: '06',
    title: 'FAST DEPLOYMENT',
    description: 'We build, polish, and deploy your website quickly so you can start getting leads.',
  },
];

export const HOW_IT_WORKS: WorkStep[] = [
  {
    step: '01',
    title: 'YOU TELL US',
    description: 'Tell us about your business and what you want.',
    detail: 'Share your vision, color preferences, reference websites, and key details over a quick WhatsApp chat or project brief form.',
  },
  {
    step: '02',
    title: 'WE PLAN',
    description: 'We understand your requirements and recommend the right structure.',
    detail: 'We outline the page hierarchy, content flow, and confirm the project timeline and transparent pricing upfront.',
  },
  {
    step: '03',
    title: 'WE BUILD',
    description: 'We design and develop your website.',
    detail: 'We build a modern, high-speed, mobile-first website with interactive components, maps, and WhatsApp integration.',
  },
  {
    step: '04',
    title: 'YOU REVIEW',
    description: 'You review the website and request agreed changes.',
    detail: 'You test the live staging site on your phone and computer, providing feedback so we can refine every detail.',
  },
  {
    step: '05',
    title: 'WE LAUNCH',
    description: 'Once everything is approved, your website goes live.',
    detail: 'We connect your domain, configure hosting, and deliver your live, ready-to-use business website.',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: '₹1,999',
    priceNum: 1999,
    subtitle: 'Ideal for simple websites, single pages, and personal portfolios.',
    pages: '1–3 pages',
    features: [
      '1–3 pages',
      'Mobile-first responsive design',
      'WhatsApp integration',
      'Google Maps',
      'Contact section',
      'Deployment',
    ],
    ctaText: 'Choose Starter →',
    websiteTypeVal: 'Starter — ₹1,999',
  },
  {
    id: 'business',
    name: 'Business',
    price: '₹3,499',
    priceNum: 3499,
    subtitle: 'Perfect for salons, restaurants, gyms, clinics & local businesses.',
    badge: 'MOST POPULAR',
    isPopular: true,
    pages: '4–7 pages',
    features: [
      '4–7 pages',
      'Custom modern design',
      'WhatsApp integration',
      'Google Maps',
      'Gallery',
      'Services / Products section',
      'Contact / enquiry form',
      'Animations',
      'Deployment',
    ],
    ctaText: 'Choose Business →',
    websiteTypeVal: 'Business — ₹3,499',
  },
  {
    id: 'professional',
    name: 'Professional',
    price: '₹5,999',
    priceNum: 5999,
    subtitle: 'Comprehensive high-impact website with advanced interactions and booking.',
    pages: '7–10+ pages',
    features: [
      '7–10+ pages',
      'Highly customized design',
      'Advanced sections',
      'Gallery',
      'WhatsApp integration',
      'Google Maps',
      'Enquiry / booking features',
      'Advanced interactions',
      'Deployment',
    ],
    ctaText: 'Choose Professional →',
    websiteTypeVal: 'Professional — ₹5,999',
  },
];

export const TARGET_AUDIENCES: TargetAudience[] = [
  {
    id: 'restaurants',
    title: 'Restaurants & Dining',
    description: 'Digital food menus, chef specials, location maps, and instant WhatsApp table reservations.',
    iconName: 'UtensilsCrossed',
    sampleWebsite: 'The Saffron Table',
    featuresNeeded: ['Interactive Menu', 'Google Maps', 'WhatsApp Booking'],
  },
  {
    id: 'cafes',
    title: 'Cafés & Bakeries',
    description: 'Cozy ambiance showcases, daily pastry drops, specialty roasts, and directions.',
    iconName: 'Coffee',
    sampleWebsite: 'Moss & Bean Café',
    featuresNeeded: ['Ambiance Gallery', 'Coffee Menu', 'Opening Hours'],
  },
  {
    id: 'beauty',
    title: 'Beauty & Hair Studios',
    description: 'Treatment price lists, style lookbooks, customer reviews, and appointment enquiries.',
    iconName: 'Sparkles',
    sampleWebsite: 'LUMÉ Beauty Studio',
    featuresNeeded: ['Service Cards', 'Style Gallery', 'WhatsApp Consults'],
  },
  {
    id: 'gyms',
    title: 'Gyms & Fitness Centers',
    description: 'High-energy training programs, coach bios, membership plans, and free trial passes.',
    iconName: 'Dumbbell',
    sampleWebsite: 'FORGE Fitness',
    featuresNeeded: ['Class Schedules', 'Trainer Showcase', 'Free Pass CTA'],
  },
  {
    id: 'fashion',
    title: 'Fashion Brands',
    description: 'Clean editorial lookbooks, seasonal drops, sizing guides, and direct order links.',
    iconName: 'Shirt',
    sampleWebsite: 'MERA Studio',
    featuresNeeded: ['Lookbook Grid', 'WhatsApp Orders', 'Collection Stories'],
  },
  {
    id: 'shops',
    title: 'Local Retail Shops',
    description: 'Product showcases, store location pins, stock enquiry lines, and promotional banners.',
    iconName: 'Store',
    sampleWebsite: 'Retail Demo',
    featuresNeeded: ['Store Hours', 'Product Catalog', 'Direct Contact'],
  },
  {
    id: 'freelancers',
    title: 'Freelancers & Consultants',
    description: 'Service packages, client proof, case study breakdowns, and direct project enquiry lines.',
    iconName: 'Laptop',
    sampleWebsite: 'Kabir Digital',
    featuresNeeded: ['Services Breakdown', 'Case Studies', 'Direct Booking'],
  },
  {
    id: 'creators',
    title: 'Creators & Photographers',
    description: 'High-resolution photo & video galleries, booking rates, and media kit links.',
    iconName: 'Camera',
    sampleWebsite: 'Rohan Visuals',
    featuresNeeded: ['Full-Bleed Gallery', 'Rate Card', 'Instant Enquiries'],
  },
  {
    id: 'developers',
    title: 'Developers & Engineers',
    description: 'Live interactive projects, GitHub activity links, tech stacks, and resume downloads.',
    iconName: 'Code',
    sampleWebsite: 'Aarav Mehta',
    featuresNeeded: ['Live Project Demos', 'Tech Stack Pills', 'Resume Download'],
  },
  {
    id: 'students',
    title: 'Students & Graduates',
    description: 'Clean academic profiles, hackathon projects, research papers, and recruiter contact.',
    iconName: 'GraduationCap',
    sampleWebsite: 'Vihaan Sharma',
    featuresNeeded: ['Project Showcase', 'Academic Timeline', 'LinkedIn Link'],
  },
  {
    id: 'startups',
    title: 'Startups & New Brands',
    description: 'High-converting product landing pages, investor-ready presentations, and waitlist forms.',
    iconName: 'Rocket',
    sampleWebsite: 'Startup Launch',
    featuresNeeded: ['Value Prop Highlights', 'Waitlist / Contact', 'Feature Demos'],
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How much does a website cost?',
    answer: 'Our launch pricing offers 3 transparent packages: 🌱 Starter at ₹1,999 (1–3 pages), ⭐ Business at ₹3,499 (4–7 pages with custom modern design, gallery, and animations - MOST POPULAR), and 🚀 Professional at ₹5,999 (7–10+ pages with advanced sections and booking features). All packages include mobile-first design, WhatsApp integration, Google Maps, and live deployment with no hidden fees.',
  },
  {
    id: 'faq-2',
    question: 'How long does a website take to build?',
    answer: 'A standard Starter or Business website is typically designed, developed, reviewed, and deployed within 3 to 7 business days once we receive your business details. Larger Professional projects generally take 7 to 10 business days.',
  },
  {
    id: 'faq-3',
    question: 'Can you build a website for my local business?',
    answer: 'Yes, absolutely! Local businesses are our specialty. We build websites for salons, restaurants, cafés, fitness gyms, dental clinics, retail shops, contractors, and service providers with built-in Google Maps directions, WhatsApp buttons, photo galleries, and opening hours.',
  },
  {
    id: 'faq-4',
    question: 'Can I request changes during development?',
    answer: 'Yes! Every project includes a dedicated review milestone before launch. You get to review the website on your phone and computer, and we will make the agreed revisions to ensure the text, colors, layouts, and images match your vision before going live.',
  },
  {
    id: 'faq-5',
    question: 'Do you provide domain and hosting assistance?',
    answer: 'We assist you in selecting and configuring high-speed, modern hosting and connecting your custom domain (e.g. yourbusiness.com). Domain registration fees and third-party hosting plans (if applicable) are paid directly to domain providers or billed separately at actual cost.',
  },
  {
    id: 'faq-6',
    question: 'Can you add WhatsApp?',
    answer: 'Yes, WhatsApp is our primary integration! Every website we build comes configured with direct WhatsApp chat triggers, pre-filled enquiry messages, or ordering links so your customers can start a conversation with you in one click.',
  },
  {
    id: 'faq-7',
    question: 'Can you add Google Maps?',
    answer: 'Yes! We embed interactive or pinpointed Google Maps so your visitors can easily see your physical store, clinic, or restaurant location and tap for turn-by-turn navigation.',
  },
  {
    id: 'faq-8',
    question: 'Can you redesign my existing website?',
    answer: 'Yes. If your current website looks dated, loads slowly, or does not look good on smartphones, we can completely redesign it from the ground up with a modern, mobile-first design while preserving your existing domain and brand identity.',
  },
  {
    id: 'faq-9',
    question: 'How do I start a project?',
    answer: 'Simply fill out the project enquiry form on this page or send us a message on WhatsApp (+91 95110 07593). Tell us about your business, the pages you need, and any reference websites you like. We will send you a clear recommendation and quote immediately.',
  },
  {
    id: 'faq-10',
    question: 'What happens after I contact ViteWEB?',
    answer: 'We will respond promptly on WhatsApp or email to discuss your requirements, confirm the best package for your budget, agree on timeline and content, and immediately begin planning your custom website.',
  },
];
